<a href="https://colab.research.google.com/github/hoon0gim/Dacon/blob/main/Project01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 상의, 하의 추출하기

In [1]:
import numpy as np
import os
import sys
import glob
from glob import glob
import cv2
import pandas as pd
#print(os.getcwd())
os.chdir('/content')
print(os.getcwd())

/content


In [2]:
from google.colab import drive
drive.mount('/content/gdrive')


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [3]:
train_data = pd.read_csv('./gdrive/My Drive/user_data/train.csv')

train_data.head()

train_df = train_data.replace('10-1', 10)
train_df2 = train_df.replace('10-2', 11)
train_df2[:20]

file_name label
0    001.png    11
1    002.png    10
2    003.png     3
3    004.png     8
4    005.png     9
5    006.png     9
6    007.png     8
7    008.png    11
8    009.png     5
9    010.png     5
10   011.png     9
11   012.png     2
12   013.png     4
13   014.png    10
14   015.png     9
15   016.png     2
16   017.png    11
17   018.png     7
18   019.png     4
19   020.png     2

In [4]:
data_list = glob('./gdrive/My Drive/user_data/train/*.png')
data_list[0]
for i in data_list:
  print(i)

./gdrive/My Drive/user_data/train/004.png
./gdrive/My Drive/user_data/train/006.png
./gdrive/My Drive/user_data/train/050.png
./gdrive/My Drive/user_data/train/019.png
./gdrive/My Drive/user_data/train/009.png
./gdrive/My Drive/user_data/train/025.png
./gdrive/My Drive/user_data/train/010.png
./gdrive/My Drive/user_data/train/020.png
./gdrive/My Drive/user_data/train/030.png
./gdrive/My Drive/user_data/train/022.png
./gdrive/My Drive/user_data/train/015.png
./gdrive/My Drive/user_data/train/035.png
./gdrive/My Drive/user_data/train/001.png
./gdrive/My Drive/user_data/train/052.png
./gdrive/My Drive/user_data/train/026.png
./gdrive/My Drive/user_data/train/043.png
./gdrive/My Drive/user_data/train/027.png
./gdrive/My Drive/user_data/train/039.png
./gdrive/My Drive/user_data/train/036.png
./gdrive/My Drive/user_data/train/017.png
./gdrive/My Drive/user_data/train/005.png
./gdrive/My Drive/user_data/train/007.png
./gdrive/My Drive/user_data/train/002.png
./gdrive/My Drive/user_data/train/

In [5]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text_to_word_sequence(data_list[0])


['gdrive', 'my', 'drive', 'user', 'data', 'train', '004', 'png']

In [6]:
label = []
for i in range(len(data_list)):
    token = text_to_word_sequence(data_list[i])
    label.append([token[6] + "." + token[7]])

label = np.array(label)
print(label[:20])
type(label)



[['004.png']
 ['006.png']
 ['050.png']
 ['019.png']
 ['009.png']
 ['025.png']
 ['010.png']
 ['020.png']
 ['030.png']
 ['022.png']
 ['015.png']
 ['035.png']
 ['001.png']
 ['052.png']
 ['026.png']
 ['043.png']
 ['027.png']
 ['039.png']
 ['036.png']
 ['017.png']]


numpy.ndarray

In [7]:
re_label = []
for i in label:
  for w in range(len(train_df2['file_name'])):
    if i == train_df2['file_name'][w]:
      re_label.append(train_df2['label'][w])
print(re_label[:10])


['8', '9', '2', '4', '5', 10, '5', '2', '8', 10]


In [8]:
# cv2 모듈을 불러 온다. 
import cv2
from matplotlib import pyplot as plt

In [9]:
data_height = 150
data_width = 150


In [10]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import cv2


# image initialization
data_height = 150
data_width = 150

batch_size = len(data_list)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

# data processing 함수 
from tensorflow.keras.preprocessing.text import text_to_word_sequence

def make_file(data_height, data_width, batch_size):
    label = []
    images = np.zeros((batch_size, data_height, data_width))
    for n, path in enumerate(data_list[:batch_size]):

    # image transform
        image = cv2.imread(data_list[n], 0)
        image = cv2.resize(image, (data_height, data_width), interpolation=cv2.INTER_LINEAR)/255
        images[n, :, :] =image
    
    label = np.array(label)
        
    return (label, images)

In [11]:
(label, images) = make_file(data_height, data_width, batch_size)

# 이미지 데이터 구조와 라벨 구조를 보기
print(images.shape, label.shape)
#print(label)

import tensorflow as tf 
from tensorflow.keras.preprocessing.text import Tokenizer



(858, 150, 150) (0,)


In [12]:
# data label encoder

items = re_label
#encoder = LabelEncoder()
#encoder.fit(items)
#label = encoder.transform(items)
#print(label)
label = tf.keras.utils.to_categorical(items)
print(label)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [13]:
label.shape

(858, 12)

In [14]:
from keras.utils import np_utils

# data split train set, test set
from sklearn.model_selection import train_test_split
x = images 
y = label

#y_train = np_utils.to_categorical(y, 4)
#y_test = np_utils.to_categorical(y, 4)
X_train, X_test, y_train, y_test = train_test_split(x, 
                                                    y, 
                                                    test_size=0.3, 
                                                    random_state=1004)

# 데이터 셋이  나누어진 것에 대한 구조보기

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)
print(y)

(600, 150, 150) (258, 150, 150)
(600, 12) (258, 12)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [15]:
  # CNN model network
model = models.Sequential()
model.add(layers.Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(data_height, data_width, 1)))
model.add(layers.MaxPooling2D(pool_size=2))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D(pool_size=2))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.Dropout(0.25))

model.add(layers.Flatten())
model.add(layers.Dense(24, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(12, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 148, 148, 32)      320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 74, 74, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 72, 72, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 36, 36, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 34, 34, 128)       73856     
                                                                 
 dropout (Dropout)           (None, 34, 34, 128)       0

In [18]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

from keras.callbacks import ModelCheckpoint,EarlyStopping

MODEL_DIR = './model/'
if not os.path.exists(MODEL_DIR):
    os.mkdir(MODEL_DIR)
    
modelpath = './model/{epoch:02d}-{val_loss:.4f}.hdf5'
checkpointer = ModelCheckpoint(filepath=modelpath, monitor='val_loss', verbose=1, save_best_only=True)
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10)

history = model.fit(X_train, y_train, validation_data=(X_test, y_test),
                                                       batch_size=1,
                                                       epochs=1000,
                   verbose=1,
                   callbacks=[early_stopping_callback,checkpointer])

Epoch 1/1000
600/600 [==============================] - ETA: 0s - loss: 1.1426 - accuracy: 0.6017
Epoch 1: val_loss improved from inf to 2.11548, saving model to ./model/01-2.1155.hdf5
600/600 [==============================] - 7s 10ms/step - loss: 1.1426 - accuracy: 0.6017 - val_loss: 2.1155 - val_accuracy: 0.4109
Epoch 2/1000
599/600 [============================>.] - ETA: 0s - loss: 1.0736 - accuracy: 0.6110
Epoch 2: val_loss improved from 2.11548 to 2.09558, saving model to ./model/02-2.0956.hdf5
600/600 [==============================] - 6s 11ms/step - loss: 1.0754 - accuracy: 0.6117 - val_loss: 2.0956 - val_accuracy: 0.4109
Epoch 3/1000
599/600 [============================>.] - ETA: 0s - loss: 0.9907 - accuracy: 0.6394
Epoch 3: val_loss did not improve from 2.09558
600/600 [==============================] - 6s 10ms/step - loss: 0.9890 - accuracy: 0.6400 - val_loss: 2.2669 - val_accuracy: 0.3915
Epoch 4/1000
599/600 [============================>.] - ETA: 0s - loss: 0.9864 - accu

In [19]:
! pip install -U tf2onnx

     |████████████████████████████████| 440 kB 5.2 MB/s 
     |████████████████████████████████| 12.8 MB 41.4 MB/s 
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 2.0
    Uninstalling flatbuffers-2.0:
      Successfully uninstalled flatbuffers-2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0+zzzcolab20220506162203 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.


In [20]:
model.save('./onnx/', include_optimizer=False)

INFO:tensorflow:Assets written to: ./onnx/assets


In [21]:
!python -m tf2onnx.convert --saved-model onnx --output model.onnx

/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-05-20 07:38:32,003 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2022-05-20 07:38:32,404 - INFO - Signatures found in model: [serving_default].
2022-05-20 07:38:32,404 - WARNING - '--signature_def' not specified, using first signature: serving_default
2022-05-20 07:38:32,405 - INFO - Output names: ['dense_1']
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2022-05-20 07:38:32,700 - WARNING - From /usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py:711: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2022-05-20 07:38:32,866 - INFO - Using ten

In [25]:
def norm_digit(img):
    # 무게 중심 좌표 추출
    m = cv2.moments(img)
    cx = m['m10'] / m['m00']
    cy = m['m01'] / m['m00']
    h, w = img.shape[:2]
    
    # affine 행렬 생성
    aff = np.array([[1, 0, w/2 - (cx + 0.5)], [0, 1, h/2 - (cy + 0.5)]], 
                   dtype=np.float32)
    
    # warpAffine을 이용해 기하학 변환
    dst = cv2.warpAffine(img, aff, (0, 0))
    return dst

def on_mouse(event, x,y, flags, params):
    global oldx, oldy
    if event==cv2.EVENT_LBUTTONDOWN:
        oldx, oldy = x,y
    elif event==cv2.EVENT_MOUSEMOVE:
        if flags&cv2.EVENT_FLAG_LBUTTON:
            cv2.line(img, (oldx,oldy), (x,y), 255, 20, cv2.LINE_AA)
            cv2.imshow('image', img)
            oldx,oldy = x,y
            
            
net = cv2.dnn.readNet('./model.onnx')
if net.empty():
    print('Network load failed')
    sys.exit()

img = np.zeros((150,150), np.uint8)
#cv2.imshow('image', img)
#cv2.setMouseCallback('image', on_mouse)

while True:
    key = cv2.waitKey()
    if key==27:
        break
    elif key == ord(' '):
        blob= cv2.dnn.blobFromImage(norm_digit(img), 1/255,(28,28))
        net.setInput(blob)
        prob = net.forward()
        
        _, maxVal, _, maxLoc = cv2.minMaxLoc(prob)
        digit = maxLoc[0]
        print(f'{digit} ({maxVal*100:4.2f}%)')
        img.fill(0)
        cv2.imshow('image',img)
    
cv2.destroyAllWindows()

KeyboardInterrupt: ignored

In [35]:
list_cor = []
net = cv2.dnn.readNet('./model.onnx')
if net.empty():
    print('Network load failed')
    sys.exit()
#
file_path = glob('./gdrive/My Drive/user_data/test/*.png')
for i in file_path:
  img = cv2.imread(i, cv2.IMREAD_GRAYSCALE)
  blob= cv2.dnn.blobFromImage(img, 1, (150, 150), (104, 117, 123),
                                  swapRB = False)
  #out = net.forward()
  #print(out.shape)

  net.setInput(blob)
  prob = net.forward()
  print(prob)
  #list_cor.append(prob)
  #img = cv.resize(img,None,fx=0.5,fy=0.5)
  _, maxVal, _, maxLoc = cv2.minMaxLoc(prob)
  digit = maxLoc[0]
  print(f'{digit} ({maxVal*100:4.2f}%)')

  #cv2.imshow('img', img)
  list_cor.append(digit)
  cv2.waitKey()
  cv2.destroyAllWindows()


[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  1.000000e+00 0.000000e+00 4.536884e-29 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00]]
5 (100.00%)
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00 5.1600547e-33
  0.0000000e+00 0.0000000e+00]]
7 (100.00%)
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
3 (100.00%)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
5 (100.00%)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
1 (100.00%)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
10 (100.00%)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
10 (100.00%)
[[0.0000000e+00 2.0595026e-34 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0000000e+00 0.0000000e+00]]
10 (100.00%)
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
3 (100.00%)
[[0.         0.         0.         0.96005803 0.         0.
  0.         0.03994199 0.         0.         0.         0.        ]]
3 (

In [63]:
label = []
for i in range(len(file_path)):
    token = text_to_word_sequence(file_path[i])
    label.append([token[6] + "." + token[7]])

label = np.array(label)
print(label[:20])
type(label)



[['054.png']
 ['064.png']
 ['185.png']
 ['019.png']
 ['001.png']
 ['188.png']
 ['010.png']
 ['104.png']
 ['154.png']
 ['030.png']
 ['088.png']
 ['062.png']
 ['199.png']
 ['174.png']
 ['120.png']
 ['172.png']
 ['056.png']
 ['012.png']
 ['151.png']
 ['182.png']]


numpy.ndarray

In [37]:
print(list_cor)
#rain_df = train_data.replace('10-1', 10)
list_cor = pd.Series(list_cor)

[5, 7, 3, 5, 1, 10, 10, 10, 3, 3, 10, 1, 2, 1, 10, 1, 2, 5, 7, 10, 5, 3, 7, 1, 3, 3, 5, 4, 10, 5, 5, 2, 7, 3, 9, 7, 5, 10, 8, 10, 4, 1, 5, 5, 7, 6, 4, 5, 2, 5, 1, 9, 11, 10, 11, 10, 1, 7, 7, 1, 3, 9, 10, 1, 11, 2, 7, 1, 9, 2, 5, 3, 5, 9, 5, 1, 3, 10, 3, 1, 5, 1, 5, 5, 5, 8, 7, 7, 8, 3, 5, 2, 5, 5, 2, 10, 9, 3, 3, 3, 3, 1, 5, 1, 9, 5, 7, 7, 10, 5, 4, 6, 5, 5, 5, 7, 5, 3, 1, 7, 10, 7, 7, 2, 1, 5, 5, 2, 9, 3, 7, 9, 6, 5, 7, 10, 5, 2, 7, 11, 11, 5, 10, 9, 11, 5, 3, 8, 10, 5, 8, 8, 5, 2, 4, 1, 5, 4, 5, 2, 3, 10, 1, 11, 10, 2, 10, 10, 10, 10, 10, 1, 10, 5, 6, 5, 5, 5, 5, 5, 10, 11, 5, 5, 10, 8, 2, 2, 5, 11, 10, 1, 9, 4, 10, 5, 4, 5, 10, 2, 3, 5, 2, 11, 7, 10, 11, 8, 11, 3, 2, 3, 3, 5, 8]


In [38]:
list_cor1 = list_cor.replace(10, '10-1')

In [39]:
list_cor2 = list_cor1.replace(11, '10-2')

In [54]:
print(list_cor2)
list_ans = list(list_cor2)
print(list_ans[1])

0      5
1      7
2      3
3      5
4      1
      ..
210    2
211    3
212    3
213    5
214    8
Length: 215, dtype: object
7


In [ ]:
#re_label = []
#for i in label:
#  for w in range(len(train_df2['file_name'])):
#    if i == train_df2['file_name'][w]:
#      re_label.append(train_df2['label'][w])
#print(re_label[:10])


In [68]:
test_data = pd.read_csv('./gdrive/My Drive/user_data/test.csv')
test_data['file_name'][0]

re_label = []
for i in test_data['file_name']:
  for w in range(len(label)):
    if i == label[w]:
      re_label.append(list_ans[w])
print(re_label[:10])


[1, '10-2', 1, 1, 9, '10-1', '10-1', 1, 2, '10-1']


In [71]:
import csv    
f = open('./gdrive/My Drive/user_data/output3.csv', 'w', encoding='utf-8', newline='')
wr = csv.writer(f)
wr.writerow(["file_name", "label"])
for i in range(len(test_data)):
  wr.writerow([test_data['file_name'][i], re_label[i]])
  #wr.writerow([1, "김정수", False])
  #wr.writerow([2, "박상미", True])
f.close()