<a href="https://colab.research.google.com/github/hoon0gim/Dacon/blob/main/Project01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 상의, 하의 추출하기

In [1]:
import numpy as np
import os
import sys
import glob
from glob import glob
import cv2
import pandas as pd
#print(os.getcwd())
os.chdir('/content')
print(os.getcwd())

/content


In [2]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [3]:
train_data = pd.read_csv('./gdrive/My Drive/user_data/train.csv')

train_data.head()

train_df = train_data.replace('10-1', 10)
train_df2 = train_df.replace('10-2', 11)
train_df2.head()

file_name label
0   001.png    11
1   002.png    10
2   003.png     3
3   004.png     8
4   005.png     9

In [22]:
data_list = glob('./gdrive/My Drive/user_data/train/*.png')
data_list[0]

'./gdrive/My Drive/user_data/train/004.png'

In [ ]:
#from tensorflow.keras.preprocessing.text import text_to_word_sequence
#text_to_word_sequence(data_list[0])


['whole', 'whole', '1', '1', 'png']

In [ ]:
#label = []
#for i in range(len(data_list)):
#    token = text_to_word_sequence(data_list[i])
#    label.append(token[0])


In [ ]:
from sklearn.preprocessing import LabelEncoder
items = label
encoder = LabelEncoder()
encoder.fit(items)
label = encoder.transform(items)

# lebel 디코딩 확인한다
encoder.inverse_transform(label)

array(['bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bottom',
       'bottom', 'bottom', 'bottom', 'bottom', 'bottom', 'bott

In [5]:
# cv2 모듈을 불러 온다. 
import cv2
from matplotlib import pyplot as plt

In [6]:
data_height = 150
data_width = 150


In [9]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import cv2


# image initialization
data_height = 150
data_width = 150

batch_size = len(data_list)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

# data processing 함수 
from tensorflow.keras.preprocessing.text import text_to_word_sequence

def make_file(data_height, data_width, batch_size):
    label = []
    images = np.zeros((batch_size, data_height, data_width))
    for n, path in enumerate(data_list[:batch_size]):

    # image transform
        image = cv2.imread(data_list[n], 0)
        image = cv2.resize(image, (data_height, data_width), interpolation=cv2.INTER_LINEAR)/255
        images[n, :, :] =image
    
    label = np.array(label)
        
    return (label, images)

In [12]:
(label, images) = make_file(data_height, data_width, batch_size)

# 이미지 데이터 구조와 라벨 구조를 보기
print(images.shape, label.shape)
#print(label)

import tensorflow as tf 
from tensorflow.keras.preprocessing.text import Tokenizer



(858, 150, 150) (0,)
[]


In [14]:
# data label encoder

items = train_df2['label']
#encoder = LabelEncoder()
#encoder.fit(items)
#label = encoder.transform(items)
#print(label)
label = tf.keras.utils.to_categorical(items)
print(label)


[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
label.shape

(858, 12)

In [17]:
from keras.utils import np_utils

# data split train set, test set
from sklearn.model_selection import train_test_split
x = images 
y = label

#y_train = np_utils.to_categorical(y, 4)
#y_test = np_utils.to_categorical(y, 4)
X_train, X_test, y_train, y_test = train_test_split(x, 
                                                    y, 
                                                    test_size=0.3, 
                                                    random_state=1004)

# 데이터 셋이  나누어진 것에 대한 구조보기

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)
print(y)

(600, 150, 150) (258, 150, 150)
(600, 12) (258, 12)
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
  # CNN model network
model = models.Sequential()
model.add(layers.Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(data_height, data_width, 1)))
model.add(layers.MaxPooling2D(pool_size=2))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D(pool_size=2))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.Dropout(0.25))

model.add(layers.Flatten())
model.add(layers.Dense(24, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(12, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 148, 148, 32)      320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 74, 74, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 72, 72, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 36, 36, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 34, 34, 128)       73856     
                                                                 
 dropout (Dropout)           (None, 34, 34, 128)       0

In [19]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

from keras.callbacks import ModelCheckpoint,EarlyStopping

MODEL_DIR = './model/'
if not os.path.exists(MODEL_DIR):
    os.mkdir(MODEL_DIR)
    
modelpath = './model/{epoch:02d}-{val_loss:.4f}.hdf5'
checkpointer = ModelCheckpoint(filepath=modelpath, monitor='val_loss', verbose=1, save_best_only=True)
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10)

history = model.fit(X_train, y_train, validation_data=(X_test, y_test),
                                                       batch_size=10,
                                                       epochs=1000,
                   verbose=1,
                   callbacks=[early_stopping_callback,checkpointer])

Epoch 1/1000
59/60 [============================>.] - ETA: 0s - loss: 2.5063 - accuracy: 0.0746
Epoch 1: val_loss improved from inf to 2.47069, saving model to ./model/01-2.4707.hdf5
60/60 [==============================] - 14s 50ms/step - loss: 2.5053 - accuracy: 0.0750 - val_loss: 2.4707 - val_accuracy: 0.0891
Epoch 2/1000
60/60 [==============================] - ETA: 0s - loss: 2.4818 - accuracy: 0.0833
Epoch 2: val_loss did not improve from 2.47069
60/60 [==============================] - 2s 38ms/step - loss: 2.4818 - accuracy: 0.0833 - val_loss: 2.4740 - val_accuracy: 0.0891
Epoch 3/1000
59/60 [============================>.] - ETA: 0s - loss: 2.4724 - accuracy: 0.0932
Epoch 3: val_loss improved from 2.47069 to 2.46315, saving model to ./model/03-2.4631.hdf5
60/60 [==============================] - 2s 35ms/step - loss: 2.4719 - accuracy: 0.0933 - val_loss: 2.4631 - val_accuracy: 0.0814
Epoch 4/1000
59/60 [============================>.] - ETA: 0s - loss: 2.4690 - accuracy: 0.0780


KeyboardInterrupt: ignored

In [ ]:
! pip install -U tf2onnx

In [ ]:
model.save('./onnx2/', include_optimizer=False)

INFO:tensorflow:Assets written to: ./onnx2/assets


In [ ]:
!python -m tf2onnx.convert --saved-model onnx2 --output model2.onnx

2022-05-10 12:29:58.750850: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-05-10 12:29:58.750891: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\user\anaconda3\lib\runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-05-10 12:30:04.746489: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-05-10 12:30:04.747660: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2022-05-10 12:30:04.748823: W tensorflow/stream_executor/pl

In [ ]:
def norm_digit(img):
    # 무게 중심 좌표 추출
    m = cv2.moments(img)
    cx = m['m10'] / m['m00']
    cy = m['m01'] / m['m00']
    h, w = img.shape[:2]
    
    # affine 행렬 생성
    aff = np.array([[1, 0, w/2 - (cx + 0.5)], [0, 1, h/2 - (cy + 0.5)]], 
                   dtype=np.float32)
    
    # warpAffine을 이용해 기하학 변환
    dst = cv2.warpAffine(img, aff, (0, 0))
    return dst

def on_mouse(event, x,y, flags, params):
    global oldx, oldy
    if event==cv2.EVENT_LBUTTONDOWN:
        oldx, oldy = x,y
    elif event==cv2.EVENT_MOUSEMOVE:
        if flags&cv2.EVENT_FLAG_LBUTTON:
            cv2.line(img, (oldx,oldy), (x,y), 255, 20, cv2.LINE_AA)
            cv2.imshow('image', img)
            oldx,oldy = x,y
            
            
net = cv2.dnn.readNet('./model2.onnx')
if net.empty():
    print('Network load failed')
    sys.exit()

img = np.zeros((150,150), np.uint8)
cv2.imshow('image', img)
cv2.setMouseCallback('image', on_mouse)

while True:
    key = cv2.waitKey()
    if key==27:
        break
    elif key == ord(' '):
        blob= cv2.dnn.blobFromImage(norm_digit(img), 1/255,(28,28))
        net.setInput(blob)
        prob = net.forward()
        
        _, maxVal, _, maxLoc = cv2.minMaxLoc(prob)
        digit = maxLoc[0]
        print(f'{digit} ({maxVal*100:4.2f}%)')
        img.fill(0)
        cv2.imshow('image',img)
    
cv2.destroyAllWindows()

error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:148: error: (-1:Backtrace) Can't infer a dim denoted by -1 in function 'cv::dnn::computeShapeByReshapeMask'


In [ ]:

net = cv2.dnn.readNet('./model2.onnx')
if net.empty():
    print('Network load failed')
    sys.exit()
#
img = cv2.imread('./stand_man/1 (41).jpeg', cv2.IMREAD_GRAYSCALE)
blob= cv2.dnn.blobFromImage(img, 1, (150, 150), (104, 117, 123),
                                swapRB = False)
#out = net.forward()
#print(out.shape)

net.setInput(blob)
prob = net.forward()
print(prob)

#img = cv.resize(img,None,fx=0.5,fy=0.5)
_, maxVal, _, maxLoc = cv2.minMaxLoc(prob)
digit = maxLoc[0]
print(f'{digit} ({maxVal*100:4.2f}%)')

cv2.imshow('img', img)

cv2.waitKey()
cv2.destroyAllWindows()


[[0. 0. 0. 1.]]
3 (100.00%)


In [ ]:
img = cv2.imread('./stand_man/1 (33).jpeg')
net = cv2.dnn.readNet('./whole_model.onnx')
if net.empty():
    print('Network load failed')
    sys.exit()
#
blob = cv2.dnn.blobFromImage(img, 1, (150,150), (104,177,123),
                            swapRB=False)
net.setInput(blob)
out = net.forward()
print(out.shape)
print(out)
detect = out[:,:]
h,w = img.shape[:2]

for i in range(detect.shape[0]):
    confidence = detect[i, 2]
    
    if confidence > 0.5:
        x1 = int(detect[i, 3]*w)
        y1 = int(detect[i, 4]*h)
        x2 = int(detect[i, 5]*w)
        y2 = int(detect[i, 6]*h)
        cv2.rectangle(img, (x1,y1), (x2,y2), (0,0,255), 2)
        text = 'Face: {:.2f}%'.format(confidence*100)
        cv2.putText(img,text, (x1,y1-2), cv2.FONT_HERSHEY_COMPLEX,
                   0.8, (0,0,255), 1, cv2.LINE_AA)
        
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()    

(3, 1)
[[0.9999012]
 [0.9970293]
 [0.999435 ]]


IndexError: index 2 is out of bounds for axis 1 with size 1